name: Issue SSL Certificates
on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

env:
  Ali_Key: ${{ secrets.ALI_KEY }}
  Ali_Secret: ${{ secrets.ALI_SECRET }}

jobs:
  issue-wildcard-certs:
    name: Issue SSL Certificates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        domain: 
          - 'terraria.ink'
          - '*.terraria.ink'
        include:
          - domain: 'terraria.ink'
            cert_name: 'TShockPluginsDocs'
            cdn_domains: 'docs.terraria.ink'
          - domain: '*.terraria.ink'
            cert_name: 'CaiBotApi'
            cdn_domains: 'raw.terraria.ink'
          - domain: '*.terraria.ink'
            cert_name: 'CaiBlog'
            cdn_domains: 'blog.terraria.ink'
    
    steps:
      - uses: Menci/acme@v2
        with:
          version: 3.0.2
          domains: ${{ matrix.domain }}
          arguments: --server letsencrypt --dns dns_ali
          output-fullchain: output/fullchain.pem
          output-key: output/key.pem
   
      - uses: Menci/deploy-certificate-to-aliyun@beta-v1
        with:
          access-key-id: ${{ secrets.ALI_KEY }}
          access-key-secret: ${{ secrets.ALI_SECRET }}
          fullchain-file: output/fullchain.pem
          key-file: output/key.pem
          certificate-name: ${{ matrix.cert_name }}
          cdn-domains: ${{ matrix.cdn_domains }}
          timeout: 10000
          retry: 3
